server:
  port: 8088

spring:
  application:
    name: JobScheduler
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/scheduler
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

org.quartz:
  jobStore:
    class: org.quartz.impl.jdbcjobstore.JobStoreTX
    driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    dataSource: myDS
    tablePrefix: QRTZ_
    useProperties: true # 이 값이 true이면 JobDataMaps에 저장되는 값이 binary가 아닌 string 값으로 저장된다.
    misfireThreshold: 60000 # 기본값 : 1분. Trigger가 misfire(불발)된 것으로 간주되는 시간이 1분이 지나면 misfire로 판단한다.
  dataSource:
    myDS:
      driver: org.h2.Driver
      URL: jdbc:h2:tcp://localhost/~/scheduler
      user: sa
      password: